#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# uim
export GTK_IM_MODULE='fcitx'
export QT_IM_MODULE='fcitx'
export XMODIFIERS='@im=fcitx'

# keyboard
xbindkeys &

# setxkbmap -layout jp &
xkbcomp -I$HOME/.xkb $HOME/.xkbmap $DISPLAY > /dev/null 2>&1

# Here LXDE is kept as default
session=${1:-lxde}
case $session in
    openbox           ) lxpanel &
                        nm-applet &
                        xsetroot -cursor_name left_ptr &
                        exec openbox-session;;
    lxde              ) export GTK_THEME=Adwaita:dark
                        copyq &
                        exec startlxde;;
    xfce4             ) export GTK_THEME=Adwaita:dark
                        #picom --config ~/.config/picom/invert.conf -b
                        picom -b
                        copyq &
                        exec startxfce4;;
    xmonad            ) xfce4-power-manager &
                        #picom --config ~/.config/picom/invert.conf -b
                        picom -b
                        nitrogen --restore &
                        fcitx5 &
                        copyq &
                        (sleep 3; conky) &
                        export GTK_THEME=Adwaita:dark
                        export _JAVA_AWT_WM_NONREPARENTING=1
                        export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=lcd'
                        if type xmonad > /dev/null 2>&1
                        then
                            exec xmonad
                        elif type my-xmonad-exe > /dev/null 2>&1
                        then
                            exec my-xmonad-exe
                        fi
                        ;;
    # No known session, try to run it as command
    *) exec $1;;
esac
